---
- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
  - name: hostname was used instead of path.
    replace:
      path: /etc/hosts
      regexp: '(\s+)old\.name\.com(\s+.*)?$'
      replace: '\nnew.name.com\2'
      backup: yes
